### ISSUE TITLE
Token grabber

### ISSUE THREAD

**Issue by Sussymoment69420** [6nz/Discord-gc-spammer#1]
It has webhook

**Comment by 6nz** [comment]
> It has webhook

What? What do you mean? Where is the webhook? Are u braindead

**Comment by 6nz** [comment]
> It has webhook

Thats a group chat spammer, it uses discord api lmao dont comment stupid things if you cant even read the code

**Comment by 6nz** [comment]
And its patched u will get rate limited after 10 group chats
