### ISSUE TITLE
API Ban Risk

### ISSUE THREAD

**Issue by StructuredObjects** [6nz/Discord-gc-spammer#2]
No Rate limit worker for the API. This can get a user’s home network banned from its API

https://github.com/6nz/Discord-gc-spammer/blob/dc19577524d4241deb4d7b7aa5d39a23a04cc113/gc%20spammer.py#L17

**Comment by 6nz** [comment]
![image](https://user-images.githubusercontent.com/74118308/219753208-2537615f-270b-4bcf-927e-fdc8fada66af.png)

**Comment by 6nz** [comment]
Its patched anyways, not just the rate limit

**Comment by StructuredObjects** [comment]
Discord API Rate Limit is been a thing before this script was even released lmfao.

**Comment by 6nz** [comment]
Ok but only rate limited after numerous group chat, so it doesnt matter

**Comment by 6nz** [comment]
Now its fully patched

**Comment by 6nz** [comment]
![Screenshot_2023-02-18-13-55-35-807_com android chrome-edit](https://user-images.githubusercontent.com/74118308/219866961-3d324caa-1113-4e4e-8c96-6866c0ebefe8.jpg)

**Comment by 6nz** [comment]
Still waiting for your answer
